### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by stefannorman** [stefannorman/home.se-download#3]
```
Traceback (most recent call last):
  File "/Users/stefannorman/projects/home.se-download/export2mbox.py", line 147, in <module>
    body.set_payload(msg_body, charset='utf-8')
  File "/Users/stefannorman/.pyenv/versions/3.7.4/lib/python3.7/email/message.py", line 315, in set_payload
    payload = payload.encode(charset.output_charset)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 117-118: surrogates not allowed
```

**Comment by stefannorman** [comment]
Added exception catching so now the imports moves along and prints error:
```
Error adding message 2109CEF8-21F4-44D5-BA45-244CB2447850
'utf-8' codec can't encode characters in position 117-118: surrogates not allowed
```

**Comment by stefannorman** [comment]
Some emails had did not have the `QComposerMSB` element.
```
Content None of message B6F14939-D9F2-4E10-B656-F95122F169BA
Content None of message E0992270-EBE0-4FD8-9DE0-7D0A78AADB0B
Content None of message 5376182D-FAD8-46CB-BCBE-AD94D1BF758D
Content None of message 2932C691-D5CE-45C2-9BC6-845A0DFD7A4D
Content None of message D0E1F903-DAAB-439A-94AE-CA4B6230EC2E
Content None of message 66CEFC7E-1DD7-4A06-A202-95F6E2835186
Content None of message 8CD93D2F-2E1A-497C-BEA7-4EBCC101EE5E
Content None of message A7AF9A3A-9B01-4C11-91BA-2429060F99AF
Content None of message 737B3037-B964-4B27-8919-D7570B143868
Content None of message 3977A13A-CAC0-4731-8951-A163AF496E4A
Content None of message 783062EF-B185-4B99-8D2E-74A5446EA391
Content None of message 418E992E-92DE-4496-80BA-D56DD72C542E
Content None of message 0375E497-E75B-45D2-97EA-16E87ADE0422
Content None of message 8EDDE850-7CC3-4B5D-A1EE-51588E216F0B
Content None of message 74E213F4-3911-4D23-96E2-035AF2F11602
Content None of message 6B9E0353-C36C-454B-A05C-927AAD595998
Content None of message 1FC16C2C-6B00-43C7-8765-D261CE25B26A
Content None of message E4AFA855-1213-4A19-9571-46AF36FEB14F
Content None of message 19B1CDA0-03D6-438C-AB73-EB17449A0B60
Content None of message F84DA06B-58DA-46AF-80CB-8CC1F5B6096C
Content None of message 4B20382B-4B0E-427F-8305-AC55D61FBEE0
Content None of message A2985AA1-6C1D-4894-AF10-D3EEB72B3B32
Content None of message 2F3987A6-FA44-42B8-AF68-A3DD43269B34
Content None of message A5970406-8CF0-4AEE-AA47-CBA16BEDC643
Content None of message D8F234EA-625A-4B7D-A222-7E33FB22F36C
Content None of message B8601EAB-7379-47B0-A673-84DB2C52107F
Content None of message 48376C69-D81D-4F0D-8115-9FD116200D84
Content None of message 45125F16-9048-44DF-B1C0-85C922784134
Content None of message 78145B0B-904D-4041-9DC1-90DBBA0D720D
Content None of message 0E967477-27FC-4ADF-9354-BA63FDE24F02
Content None of message 3F27BEF2-91DE-4337-8096-D93EBCC7E4B1
Content None of message B6278B0A-AC62-4AF6-9E14-CA26A3F69496
Content None of message E4A71C25-AA91-4407-9DE5-6B8C121E02DA
Content None of message 18B6BD7B-8609-4183-B7D1-2EC27BE9F5F2
Content None of message 6B575AA6-26B0-4DB6-9060-44EB0D8D214D
Content None of message F7972538-6DF6-4D02-8124-3A161DA589C6
Content None of message FBE2EE05-0702-4C8B-B01F-A5C1680E2608
Content None of message 5C207978-7837-4E53-A476-2F9A9441F455
Content None of message F546C040-E4AA-4EFC-B691-1EC1E5FF6FFF
Content None of message 49AB3752-73A1-431F-8A12-A0D28EA2F9D6
Content None of message 9B80B2AA-FCAB-4A69-92F2-24B7976C5DA3
```
